# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u1.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/png/系统 (9).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.tbopen = QtWidgets.QToolButton(self.centralwidget)
        self.tbopen.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/png/folder_open_72px_12180_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tbopen.setIcon(icon1)
        self.tbopen.setIconSize(QtCore.QSize(30, 30))
        self.tbopen.setAutoRaise(True)
        self.tbopen.setObjectName("tbopen")
        self.horizontalLayout.addWidget(self.tbopen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_8.addWidget(self.listWidget)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.leedit = QtWidgets.QLineEdit(self.groupBox)
        self.leedit.setMinimumSize(QtCore.QSize(0, 25))
        self.leedit.setClearButtonEnabled(True)
        self.leedit.setObjectName("leedit")
        self.horizontalLayout_13.addWidget(self.leedit)
        self.tbadd = QtWidgets.QToolButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/png/Paste_72px_556421_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tbadd.setIcon(icon2)
        self.tbadd.setIconSize(QtCore.QSize(25, 25))
        self.tbadd.setAutoRaise(True)
        self.tbadd.setObjectName("tbadd")
        self.horizontalLayout_13.addWidget(self.tbadd)
        self.tbdeete = QtWidgets.QToolButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/png/trash_72px_1187359_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tbdeete.setIcon(icon3)
        self.tbdeete.setIconSize(QtCore.QSize(25, 25))
        self.tbdeete.setAutoRaise(True)
        self.tbdeete.setObjectName("tbdeete")
        self.horizontalLayout_13.addWidget(self.tbdeete)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.horizontalLayout_12.addWidget(self.groupBox_5)
        self.groupBox1 = QtWidgets.QGroupBox(self.tab)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox1)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lewidth = QtWidgets.QLineEdit(self.groupBox_2)
        self.lewidth.setMinimumSize(QtCore.QSize(0, 24))
        self.lewidth.setMaxLength(4)
        self.lewidth.setAlignment(QtCore.Qt.AlignCenter)
        self.lewidth.setClearButtonEnabled(True)
        self.lewidth.setObjectName("lewidth")
        self.horizontalLayout_2.addWidget(self.lewidth)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leheight = QtWidgets.QLineEdit(self.groupBox_2)
        self.leheight.setMinimumSize(QtCore.QSize(0, 24))
        self.leheight.setMaxLength(4)
        self.leheight.setAlignment(QtCore.Qt.AlignCenter)
        self.leheight.setClearButtonEnabled(True)
        self.leheight.setObjectName("leheight")
        self.horizontalLayout_3.addWidget(self.leheight)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.sbnum = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbnum.setMinimumSize(QtCore.QSize(45, 24))
        self.sbnum.setMaximumSize(QtCore.QSize(45, 16777215))
        self.sbnum.setAlignment(QtCore.Qt.AlignCenter)
        self.sbnum.setMinimum(1)
        self.sbnum.setMaximum(999)
        self.sbnum.setProperty("value", 200)
        self.sbnum.setObjectName("sbnum")
        self.horizontalLayout_7.addWidget(self.sbnum)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_14.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_14.addWidget(self.checkBox_2)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox1)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.sbmax = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbmax.setMinimumSize(QtCore.QSize(45, 24))
        self.sbmax.setMaximumSize(QtCore.QSize(45, 16777215))
        self.sbmax.setWrapping(False)
        self.sbmax.setAlignment(QtCore.Qt.AlignCenter)
        self.sbmax.setMinimum(1)
        self.sbmax.setMaximum(999)
        self.sbmax.setProperty("value", 300)
        self.sbmax.setObjectName("sbmax")
        self.horizontalLayout_5.addWidget(self.sbmax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.sbmin = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbmin.setMinimumSize(QtCore.QSize(45, 24))
        self.sbmin.setMaximumSize(QtCore.QSize(45, 16777215))
        self.sbmin.setAlignment(QtCore.Qt.AlignCenter)
        self.sbmin.setMinimum(1)
        self.sbmin.setMaximum(999)
        self.sbmin.setProperty("value", 16)
        self.sbmin.setObjectName("sbmin")
        self.horizontalLayout_4.addWidget(self.sbmin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.sbrange = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbrange.setMinimumSize(QtCore.QSize(45, 24))
        self.sbrange.setMaximumSize(QtCore.QSize(45, 16777215))
        self.sbrange.setAlignment(QtCore.Qt.AlignCenter)
        self.sbrange.setMinimum(1)
        self.sbrange.setProperty("value", 1)
        self.sbrange.setObjectName("sbrange")
        self.horizontalLayout_6.addWidget(self.sbrange)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox1)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lefont = QtWidgets.QLineEdit(self.groupBox_4)
        self.lefont.setMinimumSize(QtCore.QSize(0, 24))
        self.lefont.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lefont.setClearButtonEnabled(True)
        self.lefont.setObjectName("lefont")
        self.horizontalLayout_8.addWidget(self.lefont)
        self.tbfont = QtWidgets.QToolButton(self.groupBox_4)
        self.tbfont.setMinimumSize(QtCore.QSize(0, 24))
        self.tbfont.setObjectName("tbfont")
        self.horizontalLayout_8.addWidget(self.tbfont)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lemask = QtWidgets.QLineEdit(self.groupBox_4)
        self.lemask.setMinimumSize(QtCore.QSize(0, 24))
        self.lemask.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lemask.setClearButtonEnabled(True)
        self.lemask.setObjectName("lemask")
        self.horizontalLayout_9.addWidget(self.lemask)
        self.tbmask = QtWidgets.QToolButton(self.groupBox_4)
        self.tbmask.setMinimumSize(QtCore.QSize(0, 24))
        self.tbmask.setObjectName("tbmask")
        self.horizontalLayout_9.addWidget(self.tbmask)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.ledelete = QtWidgets.QLineEdit(self.groupBox_4)
        self.ledelete.setMinimumSize(QtCore.QSize(0, 24))
        self.ledelete.setMaximumSize(QtCore.QSize(175, 16777215))
        self.ledelete.setClearButtonEnabled(True)
        self.ledelete.setObjectName("ledelete")
        self.horizontalLayout_10.addWidget(self.ledelete)
        self.tbdelete = QtWidgets.QToolButton(self.groupBox_4)
        self.tbdelete.setMinimumSize(QtCore.QSize(0, 24))
        self.tbdelete.setObjectName("tbdelete")
        self.horizontalLayout_10.addWidget(self.tbdelete)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.lesave = QtWidgets.QLineEdit(self.groupBox_4)
        self.lesave.setMinimumSize(QtCore.QSize(0, 24))
        self.lesave.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lesave.setClearButtonEnabled(True)
        self.lesave.setObjectName("lesave")
        self.horizontalLayout_15.addWidget(self.lesave)
        self.tbsave = QtWidgets.QToolButton(self.groupBox_4)
        self.tbsave.setMinimumSize(QtCore.QSize(0, 24))
        self.tbsave.setObjectName("tbsave")
        self.horizontalLayout_15.addWidget(self.tbsave)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line = QtWidgets.QFrame(self.groupBox1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.bcloud = QtWidgets.QPushButton(self.groupBox1)
        self.bcloud.setMinimumSize(QtCore.QSize(0, 46))
        self.bcloud.setObjectName("bcloud")
        self.verticalLayout_7.addWidget(self.bcloud)
        self.frame_3 = QtWidgets.QFrame(self.groupBox1)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 7))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 7))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.progressBar = QtWidgets.QProgressBar(self.frame_3)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_12.addWidget(self.groupBox1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_12.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "词云"))
        self.label.setText(_translate("MainWindow", "选择文件 "))
        self.tbopen.setText(_translate("MainWindow", "..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "排除词"))
        self.tbadd.setText(_translate("MainWindow", "..."))
        self.tbdeete.setText(_translate("MainWindow", "..."))
        self.groupBox1.setTitle(_translate("MainWindow", "词云选项"))
        self.label_2.setText(_translate("MainWindow", "长"))
        self.lewidth.setText(_translate("MainWindow", "1920"))
        self.label_3.setText(_translate("MainWindow", "宽"))
        self.leheight.setText(_translate("MainWindow", "1080"))
        self.label_7.setText(_translate("MainWindow", "单词数量"))
        self.checkBox.setText(_translate("MainWindow", "黑色背景"))
        self.checkBox_2.setText(_translate("MainWindow", "切换编码"))
        self.label_4.setText(_translate("MainWindow", "最大字号"))
        self.label_5.setText(_translate("MainWindow", "最小字号"))
        self.label_6.setText(_translate("MainWindow", "步值"))
        self.label_8.setText(_translate("MainWindow", "字体路径"))
        self.lefont.setPlaceholderText(_translate("MainWindow", "默认仿宋，选择ttf字体"))
        self.tbfont.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "形状"))
        self.tbmask.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "排除词"))
        self.tbdelete.setText(_translate("MainWindow", "..."))
        self.label_11.setText(_translate("MainWindow", "生成路径"))
        self.tbsave.setText(_translate("MainWindow", "..."))
        self.bcloud.setText(_translate("MainWindow", "生成词云"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "词云"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "排除词"))

import pic_rc
